### ISSUE TITLE
自定义创建问题

### ISSUE THREAD

**Issue by luban250** [XiaoMi/naftis#24]
我创建了个自定义模板，跟traffic shift一样，就是把reviews改变为了{.Host},创建模板任务时填完参数提交就报错了，报400，提示namespace参数为空

**Comment by sevennt** [comment]
能否提供下你自定义模板的内容？

**Comment by sevennt** [comment]
@luban250 是这样：
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{.Host}}
spec:
  hosts:
  - {{.Host}} # 双花括号
  http:
  - route:
    - destination:
        host: {{.Host}}
        subset: {{.DestinationSubset1}}
      weight: {{.Weight1}}
    - destination:
        host: {{.Host}}
        subset: {{.DestinationSubset2}}
      weight: {{.Weight2}}
```

还是这样：
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{.Host}}
spec:
  hosts:
  - {.Host} # 单花括号
  http:
  - route:
    - destination:
        host: {{.Host}}
        subset: {{.DestinationSubset1}}
      weight: {{.Weight1}}
    - destination:
        host: {{.Host}}
        subset: {{.DestinationSubset2}}
      weight: {{.Weight2}}
```
